backend:
  name: git-gateway

media_folder: source/images/uploads
public_folder: /images/uploads

collections:
  - name: artists
    identifier_field: name
    label: Artist
    folder: data/artists/
    extension: .html.md
    format: frontmatter
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{name}}"
    fields:
      - { label: Name, name: name, widget: string }
      - { label: Publish Date, name: date, widget: datetime }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - { label: Body, name: body, widget: markdown }
