backend:
  name: git-gateway

media_folder: source/images/uploads
public_folder: /images/uploads

collections:
  - name: artist
    label: Artist
    format: yml
    extension: yml
    folder: data/artists/
    create: true
    slug: "{{title}}"
    fields:
      - { label: Title, name: title, widget: string, required: true }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Image, name: image, widget: image, required: true }
      - { label: Body, name: body, widget: markdown }

  - name: merchandise
    label: Merchandise
    folder: data/merchandise/
    format: yml
    extension: yml
    create: true
    fields:
      - { label: Name, name: name, widget: string, required: true }
      - { label: Image, name: image, widget: image, required: true }
